### ISSUE TITLE
Fatal signal 6 (SIGABRT ) after calling : new PickerDialogFragment().show(getFragmentManager(), "dialog");

### ISSUE THREAD

**Issue by BatshevaR** [svenwiegand/time-duration-picker#10]
what can it be?
thanks for the awesome library!

**Comment by BatshevaR** [comment]
i found my bug sir, 
the problem was that i created in my project an xml file named : time_duration_picker.xml
and that did a conflict with yours probably
thanks

**Comment by svenwiegand** [comment]
Thanks for reporting that it is solved.
