### ISSUE TITLE
TimeDurationPicker.SavedState does not implement field for Creator interface

### ISSUE THREAD

**Issue by HaukeRa** [svenwiegand/time-duration-picker#12]
Because of this the view restore procedure can crash (for me it started crashing after switching to the android support libraries' Fragments.

For reference, this is the weird Exception that is produced: "java.lang.RuntimeException: Parcel android.os.Parcel@33bc0fc: Unmarshalling unknown type code 3145776 at offset 1340"

Of course the code and the offset may vary depending on your view hierarchy.

This is the correct implementation:
`public static class SavedState extends BaseSavedState {
        final String durationInput;

        public SavedState(Parcelable superState, String durationInput) {
            super(superState);
            this.durationInput = durationInput;
        }

        @SuppressWarnings("unused")
        public SavedState(Parcel source) {
            super(source);
            durationInput = source.readString();
        }

        @Override
        public void writeToParcel(Parcel out, int flags) {
            super.writeToParcel(out, flags);
            out.writeString(durationInput);
        }

        public static final Parcelable.Creator<SavedState> CREATOR
                = new Parcelable.Creator<SavedState>() {
            public SavedState createFromParcel(Parcel in) {
                return new SavedState(in);
            }

            public SavedState[] newArray(int size) {
                return new SavedState[size];
            }
        };
    }

The only thing that is changed is the added CREATOR field.

**Comment by HaukeRa** [comment]
Pull request: https://github.com/svenwiegand/time-duration-picker/pull/13

**Comment by svenwiegand** [comment]
Thanks for the report and your pull request. Merged! Published 1.1.3.
