### ISSUE TITLE
Bug for RTL languages

### ISSUE THREAD

**Issue by henrichg** [svenwiegand/time-duration-picker#20]
![screenshot_20180912-101048](https://user-images.githubusercontent.com/4045914/45432948-63831d00-b6ab-11e8-91d6-00e1ba973386.jpg)

Library version: 1.1.3

Called is:
`mValueDialog = new TimeDurationPickerDialog(context, 
    new TimeDurationPickerDialog.OnDurationSetListener() { ... },
    iValue * 1000, TimeDurationPicker.HH_MM_SS);
mValueDialog.show();`

Locale is system locale.

**Comment by henrichg** [comment]
Fixed myself. [Fix si in this file](https://drive.google.com/file/d/1naJSmnFyt8-0-ohnm7DtYgTlxz0-Y9sm/view?usp=drivesdk)

**Comment by safakge** [comment]
Fixed it in my our code by subclassing `TimeDurationPickerDialogFragment`, and overriding the onStart method as follows:

```
@Override
public void onStart() {
    super.onStart();
    if (getResources().getConfiguration().getLayoutDirection() == View.LAYOUT_DIRECTION_RTL) {
        Dialog dialog = getDialog();

        int clearId = R.id.clear;
        int backspaceId = R.id.backspace;

        View clearButton = dialog.findViewById(clearId);
        View backspaceButton = dialog.findViewById(backspaceId);

        backspaceButton.setScaleX(-1); // flip image horizontally

        RelativeLayout.LayoutParams clearParams = (RelativeLayout.LayoutParams) clearButton.getLayoutParams();
        clearParams.removeRule(RelativeLayout.ALIGN_PARENT_RIGHT);
        clearParams.addRule(RelativeLayout.ALIGN_PARENT_END);

        RelativeLayout.LayoutParams backspaceParams = (RelativeLayout.LayoutParams) backspaceButton.getLayoutParams();
        backspaceParams.removeRule(RelativeLayout.LEFT_OF);
        backspaceParams.addRule(RelativeLayout.START_OF, clearId);
    }
}
```
