### ISSUE TITLE
JCenter sunset is announced; please republish library versions to Maven Central

### ISSUE THREAD

**Issue by dejan2609** [svenwiegand/time-duration-picker#24]
**_Rationale_**: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Quote (from a link above):
> **_May 1st | Bintray, JCenter, GoCenter, and ChartCenter services will no longer be available_**

@svenwiegand let me know if I can help you with this.

**Comment by GabeK0** [comment]
Looks like somebody uploaded a fork to Jitpack. It's working for me at the time of writing this comment

https://jitpack.io/p/zaplitny/time-duration-picker

**Comment by czlucius** [comment]
For those getting AndroidX conflicts as this library is using the Android Support Library, it seems that a fork of this project has been adapted to AndroidX, and a build is available on JitPack.

https://jitpack.io/#Burtan/time-duration-picker/660ca33b70

**Comment by czlucius** [comment]
```
https://jitpack.io/#Burtan/time-duration-picker/660ca33b70
```
works for me

**Comment by czlucius** [comment]
```
	        implementation 'com.github.Burtan:time-duration-picker:660ca33b70'
```
works for me

**Comment by dejan2609** [comment]
JCenter was closed on August 15th, 2024. Link: https://jfrog.com/blog/jcenter-sunset

I'll close this issue now (see comments above for solution(s)/workaround(s))
