### ISSUE TITLE
is it possible to customize picker to show only hh and mm without seconds?

### ISSUE THREAD

**Issue by Karthik2007** [svenwiegand/time-duration-picker#3]
Thanks for this library. It is really cool. Only issue  am facing is to enter time since it starts from seconds. even for setting one hour , i have to press 1 and five 0s.

**Comment by svenwiegand** [comment]
At the moment that's not possible. But this sounds like a feature request...

**Comment by anishbajpai014** [comment]
I would like to work on this feature. I'm thinking of customizing the library to provide hh:mm:ss, hh:mm and mm:ss.

**Comment by svenwiegand** [comment]
Sounds great @anishbajpai014. As you might have guessed I'm currently lacking time on this. Would you be willing to create a pull request?

**Comment by anishbajpai014** [comment]
Sure. I'll create a pull request once I'm done.

**Comment by spacedema** [comment]
Hi. Thanks for this library. I can't override setTimeUnits method. I get error: method does not override or implement a method from a supertype.

**Comment by anishbajpai014** [comment]
Are you adding the repo from JCenter? setTimeUnits was only recently added and hasn't been updated on JCenter yet. You can try downloading the library and adding it as a module. @svenwiegand will update the library on JCenter soon.

**Comment by spacedema** [comment]
Thanks for the answer. Yes, I'm adding repo from JCenter.

**Comment by svenwiegand** [comment]
Published new version `1.1.0` to JCenter.

**Comment by spacedema** [comment]
Many thanks!
