### ISSUE TITLE
Pressing dialog ok without time change resets time

### ISSUE THREAD

**Issue by spacedema** [svenwiegand/time-duration-picker#5]
Hi.

I'm using dialog with minutes and seconds
protected int setTimeUnits() { return TimeDurationPicker.MM_SS; }
protected long getInitialDuration() { return 30000 } //30 seconds

1. Open dialog
2. Press ok wihtout any changes 
3. Getting duration = 0 in onDurationSet method. 

Thanks

**Comment by svenwiegand** [comment]
Thanks for this bug report. I've fixed the problem in version 1.1.1. So after updating your dependency this should work fine.
