### ISSUE TITLE
Returning the duration from the fragment

### ISSUE THREAD

**Issue by minorsecond** [svenwiegand/time-duration-picker#6]
I'm new to Android dev so this is probably a really easy question, but how does one get the duration from the TimePicker fragment?

I've got the TimePicker.java fragment in the directory with my activity. The activity successfully opens the fragment when the user long clicks on some text, but I can't figure out how to return the duration value from the fragment back to the activity. I spent a few hours yesterday messing around with interfaces but never got it to work.

**Comment by svenwiegand** [comment]
Which class are you using? Are you using the time picker directly (class `TimeDurationPicker`) or the dialog fragment (`TimeDurationPickerDialogFragment`)?

**Comment by minorsecond** [comment]
I'm using `TimeDurationPickerDialogFragment`. Completely unchanged except for the units, which I'ved changed to `MM_SS`.

**Comment by svenwiegand** [comment]
You need to override the fragment's `onDurationSet()` method. See the example in the [`README.md`](https://github.com/svenwiegand/time-duration-picker/blob/master/README.md).

This might seem inconvenient, but as you get used to Android you'll learn, that there is no other way on interacting with fragments than deriving own classes from them. This is due to configuration changes (e.g. device orientation change) where the activity itself will be destroyed and recreated, but the fragments will be serialized and restored.

Hope this helps?

**Comment by minorsecond** [comment]
I'm assuming you're referring to 

`@Override
    public void onDurationSet(TimeDurationPicker view, long duration) {
        DurationToast.show(getActivity(), duration);
    }
}`?

I've got that in the fragment, and I'm able to get a Toast notification to work but that's about it. I don't want to take up too much of your time with teaching me something I can learn on my own, so do you have any suggestions of reading I can do to figure this out? Thanks!

**Comment by svenwiegand** [comment]
Where do you need the entered duration? In your `Activity`?

**Comment by minorsecond** [comment]
Yes sir.

**Comment by svenwiegand** [comment]
Try the following:

1. In your `Activity` class (lets assume it is called `MyActivity`) add an event handler method e.g. like 
    ```java
    protected void onDurationSet(long duration) {
      // do something with the duration here
    }
    ```
2. Implement the `onDurationSet()` method of the fragment to forward the result to the activity like this:
    ```java
    @Override public void onDurationSet(TimeDurationPicker view, long duration) {
      ((MyActivity) getActivity()).onDurationSet(duration);
    }
    ```

Now you can use the duration in your activity.

The [Fragments Guide](https://developer.android.com/guide/components/fragments.html) in the Android developer documentation is a good read -- especially the section [Communicating with the Activity](https://developer.android.com/guide/components/fragments.html#CommunicatingWithActivity) addresses your current problem.

Did this help?

**Comment by minorsecond** [comment]
That did it! Thank you so much.

**Comment by svenwiegand** [comment]
Happy I was able to help.
